/**
 * Post-build script that transforms the generated Chrome manifest
 * from MV2 format (output by neutrino-webextension) to MV3 format.
 *
 * Transforms:
 * - "browser_action" → "action"
 * - Ensures "background" uses service_worker format
 * - Any other MV2→MV3 field mappings needed
 */

const path = require('path')
const fs = require('fs')

const chromePath = path.join(__dirname, '../build/chrome')
const manifestPath = path.join(chromePath, 'manifest.json')

if (!fs.existsSync(manifestPath)) {
  console.log('[chrome-mv3-fix] No build/chrome/manifest.json found, skipping.')
  process.exit(0)
}

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))

// 1. Convert "browser_action" → "action"
if (manifest.browser_action) {
  manifest.action = manifest.browser_action
  delete manifest.browser_action
  console.log('[chrome-mv3-fix] Converted browser_action → action')
}

// 2. Also remove "page_action" if present (merged into "action" in MV3)
if (manifest.page_action) {
  // Merge into action if action doesn't exist yet
  if (!manifest.action) {
    manifest.action = manifest.page_action
  }
  delete manifest.page_action
  console.log('[chrome-mv3-fix] Removed page_action (merged into action)')
}

// 3. Convert background scripts array to service_worker format
//    neutrino-webextension outputs { scripts: ["polyfill.js", "runtime.js", "bg.js"] }
//    MV3 only allows a single service_worker file, so we generate a wrapper
//    that importScripts() all the original scripts in order.
if (manifest.background && manifest.background.scripts) {
  const scripts = manifest.background.scripts
  if (scripts.length === 1) {
    manifest.background = {
      service_worker: scripts[0],
      type: 'module'
    }
  } else {
    // Generate a wrapper that loads all scripts in the correct order
    const imports = scripts.map(s => {
      const src = s.startsWith('/') ? s : '/' + s
      return `importScripts('${src}');`
    }).join('\n')
    const wrapperPath = path.join(chromePath, 'background.js')
    fs.writeFileSync(wrapperPath, imports + '\n', 'utf8')
    manifest.background = {
      service_worker: 'background.js'
      // Note: omit "type": "module" because importScripts is not allowed in module workers
    }
    console.log('[chrome-mv3-fix] Generated background.js wrapper for ' + scripts.length + ' scripts')
  }
  console.log('[chrome-mv3-fix] Converted background.scripts → service_worker')
} else if (manifest.background && manifest.background.page) {
  // If background is a page, convert to service_worker
  manifest.background = {
    service_worker: 'background.js'
  }
  console.log('[chrome-mv3-fix] Converted background.page → service_worker')
}

// 4. Verify content_scripts are present (generated by neutrino-webextension)
if (!manifest.content_scripts || manifest.content_scripts.length === 0) {
  console.warn(
    '[chrome-mv3-fix] WARNING: No content_scripts found in manifest! ' +
    'New tabs will NOT have Saladict injected automatically. ' +
    'Check neutrino-webextension config in .neutrinorc.js.'
  )
}

// 5. Convert MV2 "options_ui" if it still has "chrome_style"
if (manifest.options_ui && manifest.options_ui.chrome_style !== undefined) {
  delete manifest.options_ui.chrome_style
  console.log('[chrome-mv3-fix] Removed deprecated options_ui.chrome_style')
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8')
console.log('[chrome-mv3-fix] Chrome manifest MV3 transform complete.')

// 4. Copy declarative-net-request rules into build output
const dnrSrc = path.join(__dirname, '../src/declarative-net-request/rules.json')
const dnrDestDir = path.join(chromePath, 'declarative-net-request')
const dnrDest = path.join(dnrDestDir, 'rules.json')

if (fs.existsSync(dnrSrc)) {
  if (!fs.existsSync(dnrDestDir)) {
    fs.mkdirSync(dnrDestDir, { recursive: true })
  }
  fs.copyFileSync(dnrSrc, dnrDest)
  console.log('[chrome-mv3-fix] Copied declarative-net-request/rules.json to build output.')
} else {
  console.warn('[chrome-mv3-fix] WARNING: src/declarative-net-request/rules.json not found, skipping DNR copy.')
}
